rootProject.buildFileName = "build.gradle.kts"

include(":app")
include(":core")
include(":domain")
include(":data")
include(":common")
include(":dataPreference")
include(":dataCore")
include(":settings")
include(":mainNavigation")
include(":tasks")
include(":taskdetail")
include(":base")
include(":about")
include(":addedit")
include(":search")
include(":setting")
include(":splash")
include(":statistics")
include(":main")
include(":work")
include(":seedDatabase")
include(":downloadModule")
include(":appNavigation")

enableFeaturePreview("GRADLE_METADATA")
